### ISSUE TITLE
Fix the 12-column layout slides in the Bootstrap lesson

### ISSUE THREAD

**Issue by Dangeranger** [alexch/codelikethis#27]
Some of the content in the slides was found to be incorrectly written as it relates to creating a nav bar that is 100% on a mobile layout and 25% on a desktop layout.

Content to correct: https://github.com/alexch/codelikethis/blob/master/public/lessons/www/bootstrap_development.md#example

```css
@media screen and (min-width:768px){
  .sidebar{
    width:100%;
  }
}
@media screen and (min-width:992px){
  .nav{
    width:25%;
  }
}
```
